[build]
nodeVersion = "18.x"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 15
startupTimeout = 300
restartPolicyType = "on_failure"